name: Jekyll site CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:4.2.2 /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build"
    - name: GitHub Pages
      run: |
        mkdir /tmp/github-pages-ponicsru
        git clone --branch main https://$GH_PAT@github.com/ponicsru/ponicsru.github.io /tmp/github-pages-ponicsru
        cp -r ${{ github.workspace }}/_site/* /tmp/github-pages-ponicsru/
        cd /tmp/github-pages-ponicsru/
        git add .
        git commit -m "Generation" --author="Actions"
      env:
        GH_PAT: ${{ secrets.IOPAT }}